DROP DATABASE IF EXISTS Alimenta_tu_Corazon;
CREATE DATABASE IF NOT EXISTS Alimenta_tu_Corazon;
USE Alimenta_tu_Corazon;

CREATE TABLE NACIONALIDADES
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE SEXOS
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE TALLERES
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE DOMICILIOS
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    CALLE  VARCHAR(30),
    NUMERO INT
);

CREATE TABLE SITUACIONES_LABORALES
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE SITUACIONES_FAMILIARES
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE NIVELES_POBREZA
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE ESTADOS_SALUD
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE DISPONIBILIDAD_RECURSOS
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);


CREATE Table INGREDIENTES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    ID_COMIDA INT,
    CONSTRAINT `INREDIENTES->COMIDAS` FOREIGN KEY (ID_COMIDA) REFERENCES MENU(ID) 
);

CREATE TABLE MENUES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    DESCRIPCION TEXT,
    ID_INGREDIENTES INT);
    
    CREATE TABLE VOLUNTARIOS(
        ID int AUTO_INCREMENT PRIMARY KEY,
        NOMBRE VARCHAR(50),
        APELLIDO VARCHAR(50),
        ID_ROL INT 
    );
CREATE Table INGREDIENTES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    ID_COMIDA INT,
    CONSTRAINT `INREDIENTES->COMIDAS` FOREIGN KEY (ID_COMIDA) REFERENCES MENU(ID) 
);

    CREATE TABLE ROLES(
        ID int AUTO_INCREMENT PRIMARY KEY,
        NOMBRE VARCHAR(50),
        DESCRIPCION TEXT
    );

    CREATE TABLE DONACIONES(
        ID INT AUTO_INCREMENT PRIMARY KEY,
        NOMBRE VARCHAR(50),
        APELLIDO VARCHAR(50),
        FECHA DATE,
        CANTIDAD INT,
        CONSTRAINT `ID_MONEDA->MONEDAS` FOREIGN KEY (ID_)
    );

    CREATE TABLE MONEDAS(
        ID INT AUTO_INCREMENT PRIMARY KEY,
        NOMBRE VARCHAR(50),
        DESCRIPCION TEXT
    );
    