DROP DATABASE IF EXISTS Alimenta_tu_Corazon;
CREATE DATABASE IF NOT EXISTS Alimenta_tu_Corazon;
USE Alimenta_tu_Corazon;

CREATE TABLE NACIONALIDADES
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE SEXOS
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE TALLERES
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE DOMICILIOS
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    CALLE  VARCHAR(30),
    NUMERO INT
);

CREATE TABLE SITUACIONES_LABORALES
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE SITUACIONES_FAMILIARES
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE NIVELES_POBREZA
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE ESTADOS_SALUD
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);

CREATE TABLE DISPONIBILIDAD_RECURSOS
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(30),
    DESCRIPCION TEXT
);
